theme: jekyll-theme-cayman
title: Lara Clasen | Data Science Portfolio
description: Explore my projects on this website. 
About Me:

> - Lara Clasen<br/>
> - Graduate student at Bellevue University, expected graduation date of May 30, 2020<br/>
> - 2 years of data science experience

Contact Information:
> - Location: Minneapolis, MN<br/>
> - <a href = "mailto: lclasen@my365.bellevue.edu">Email</a><br/>
> - [LinkedIn](https://www.linkedin.com/in/laraclasen/)<br/>
